language: python
cache: pip
sudo: false

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6

install:
 - pip install -U pip
 - pip install -U flake8
 - pip install -U black

script:
 # Static analysis
 - flake8 --statistics --count .
 - black --check --diff .
