language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6

install:
 - pip install -U pip
 - pip install -U black flake8
 - pip install -U -r requirements.txt

script:
 # Static analysis
 - flake8 --statistics --count .
 - black --check --diff .
