language: python

python:
 - pypy
 - pypy3
 - 2.7
 - 3.4
 - 3.5
 - 3.6

sudo: false

install:
 - pip install pep8 pyflakes

script:
 # Pretend tests
 - pep8 --statistics --count .
 - pyflakes .

matrix:
  fast_finish: true
