language: python

python:
 - pypy
 - pypy3
 - 2.7
 - 3.4
 - 3.5
 - 3.6
 - 3.7-dev

sudo: false

install:
 - pip install flake8

script:
 # Static analysis
 - flake8 --statistics --count .

matrix:
  fast_finish: true
