language: python
cache: pip
sudo: false

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6
    - python: 3.5
    - python: 3.4

install:
 - pip install -U pip
 - pip install -U flake8

script:
 # Static analysis
 - flake8 --statistics --count .
